// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAIttPBf4yebY8KRqUP6EZ7SG9sGVxjZs',
    appId: '1:998435651008:web:7499818acc2dc3c2085c25',
    messagingSenderId: '998435651008',
    projectId: 'muse-4e461',
    authDomain: 'muse-4e461.firebaseapp.com',
    databaseURL: 'https://muse-4e461-default-rtdb.firebaseio.com',
    storageBucket: 'muse-4e461.appspot.com',
    measurementId: 'G-971W09E5ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2YCbEpDDWeFoqmVclKsC8eFXK6f0UpXQ',
    appId: '1:998435651008:android:dc2740f15d40f266085c25',
    messagingSenderId: '998435651008',
    projectId: 'muse-4e461',
    databaseURL: 'https://muse-4e461-default-rtdb.firebaseio.com',
    storageBucket: 'muse-4e461.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFeaA59hhQ8ggwVIZKwpVD4CV4Q3aYlzE',
    appId: '1:998435651008:ios:e796cc77e0e03451085c25',
    messagingSenderId: '998435651008',
    projectId: 'muse-4e461',
    databaseURL: 'https://muse-4e461-default-rtdb.firebaseio.com',
    storageBucket: 'muse-4e461.appspot.com',
    iosClientId: '998435651008-ku3koahv1hu15kqvmfan4hqj9n2bonnd.apps.googleusercontent.com',
    iosBundleId: 'com.kenandev.muse',
  );
}
